name: GitHub Pages
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: jetli/trunk-action@v0.1.0
        with:
          version: "latest"

      - uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: "latest"

      - name: Build
        run: |
          trunk build --release --public-url=budoux-rs
        working-directory: ./examples/demo

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/demo/dist
          force_orphan: true
